Moved super call to bottom of Options constructor
A bad interaction between param and nosetests would inexplicably cause
 AttributeError: 'Options' object has no attribute 'kwargs in
 Options.__repr__ when running nosetests.